version: 0.2
env:
  parameter-store:
    SONAR_TOKEN: "/devsecops/sonar/token"
  variables:
    APP_PORT: "5000"
    SONAR_PROJECT_KEY: "devsecops-poc"
    ZAP_IMAGE: "ghcr.io/zaproxy/zaproxy:stable"
    ARTIFACT_NAME: "app.jar"
    ZAP_THRESHOLD: "MEDIUM"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Creating verified ZAP configuration..."
      - mkdir -p zap/reports
      - |
        printf "exclude\t.*static/.*\tExclude static files\n" > zap/zap.conf
        printf "progress\t100\n" >> zap/zap.conf
        printf "rules\t10011=IGNORE\tCookie Without Secure Flag\n" >> zap/zap.conf
        printf "rules\t10015=IGNORE\tX-Content-Type-Options\n" >> zap/zap.conf
        printf "rules\t40012=WARN\tCSP Header\n" >> zap/zap.conf
      - echo "ZAP config file created with contents:"
      - cat zap/zap.conf
      - echo -e "\nHex dump verification:"
      - hexdump -C zap/zap.conf  # Verify tabs are present

  pre_build:
    commands:
      - export SONAR_TOKEN=$(aws ssm get-parameter --name "/devsecops/sonar/token" --with-decryption --query "Parameter.Value" --output text || echo "")

  build:
    commands:
      - mvn -B clean package

  post_build:
    commands:
      - echo "Starting application..."
      - nohup java -jar target/*.jar --server.port=${APP_PORT} > app.log 2>&1 & echo $! > app.pid
      - sleep 10
      - if ! nc -zv localhost ${APP_PORT}; then echo "Application failed to start"; exit 1; fi  # Verify app is running

      - echo "Running ZAP DAST scan with debug..."
      - >
        docker run --network host --rm
        -v $(pwd)/zap:/zap/wrk:rw
        ${ZAP_IMAGE}
        zap-baseline.py -d
        -t http://localhost:${APP_PORT}
        -c /zap/wrk/zap.conf
        -r /zap/wrk/reports/report.html
        -x /zap/wrk/reports/report.xml
        -j /zap/wrk/reports/report.json
        -l ${ZAP_THRESHOLD} || [ $? -eq 2 ] && echo "ZAP scan completed with warnings"

      - echo "Copying artifacts..."
      - cp target/*.jar ${ARTIFACT_NAME}

artifacts:
  files:
    - "${ARTIFACT_NAME}"
    - "zap/reports/*"
    - "app.log"
  name: "devsecops-artifacts"

cache:
  paths:
    - "/root/.m2/**/*"
