version: 0.2

env:
  variables:
    PROJECT_KEY: "devsecops-poc"
    ORGANIZATION: "praveenmummella"
    SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:310188667383:build-notifications"
    SONAR_TOKEN_PARAM: "/devsecops/sonar/token"
    S3_BUCKET: "codepipeline-us-east-1-310188667383"

phases:
  install:
    commands:
      - echo Installing Maven...
      - yum update -y
      - yum install -y maven
      - echo "Build environment is ready"

  pre_build:
    commands:
      - echo Fetching SONAR token from Parameter Store...
      - SONAR_TOKEN=$(aws ssm get-parameter --name "$SONAR_TOKEN_PARAM" --with-decryption --query "Parameter.Value" --output text)
      - export SONAR_TOKEN
      - echo "SONAR token fetched successfully"

  build:
    commands:
      - echo Starting build...
      - mvn clean verify
      - echo "Running SonarQube (SAST)..."
      - mvn sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=$ORGANIZATION -Dsonar.login=$SONAR_TOKEN
      - echo "Running OWASP Dependency-Check (SCA)..."
      - mvn org.owasp:dependency-check-maven:check
      - echo Build completed

  post_build:
    commands:
      - echo "Publishing reports to S3..."
      - aws s3 cp target/site/jacoco/index.html s3://$S3_BUCKET/reports/jacoco/index.html --acl public-read
      - aws s3 cp target/dependency-check-report.html s3://$S3_BUCKET/reports/sca/dependency-check-report.html --acl public-read

      - echo "Sending SNS notification..."
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]; then
          STATUS="SUCCESS"
        else
          STATUS="FAILURE"
        fi

        REPORT_LINKS="Code Coverage (JaCoCo): https://$S3_BUCKET.s3.amazonaws.com/reports/jacoco/index.html\nSCA (OWASP Dependency Check): https://$S3_BUCKET.s3.amazonaws.com/reports/sca/dependency-check-report.html"

        MESSAGE="Build Status: $STATUS\nProject: $PROJECT_KEY\n$REPORT_LINKS"

        aws sns publish \
          --topic-arn "$SNS_TOPIC_ARN" \
          --subject "Build $STATUS - $PROJECT_KEY" \
          --message "$MESSAGE"

artifacts:
  files:
    - target/*.jar
    - target/*.war
    - target/site/jacoco/**
    - target/dependency-check-report.html
