version: 0.2

env:
  variables:
    SONAR_PROJECT_KEY: "devsecops-poc"
    APP_PORT: "5000"
    ZAP_IMAGE: "ghcr.io/zaproxy/zaproxy:stable"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      # Verify Docker
      - docker --version
      
      # Pull ZAP image
      - docker pull ${ZAP_IMAGE}
      
      # Install SonarScanner (with direct download URL)
      - curl -sSL -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip -qq sonar-scanner.zip -d /opt
      - rm sonar-scanner.zip
      - chmod +x /opt/sonar-scanner-*/bin/*
      - ln -s /opt/sonar-scanner-*/bin/sonar-scanner /usr/local/bin/

  pre_build:
    commands:
      - mvn dependency:go-offline -B

  build:
    commands:
      # Build and analyze
      - mvn -B clean package
      - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${SONAR_TOKEN} \
          -Dsonar.java.binaries=target/classes \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      - mvn org.owasp:dependency-check-maven:check -B

  post_build:
    commands:
      # Start application
      - nohup java -jar target/*.jar --server.port=${APP_PORT} > app.log 2>&1 & echo $! > app.pid
      - sleep 25

      # Health check
      - timeout 120 bash -c 'until curl -sSf http://localhost:${APP_PORT}/health; do sleep 5; done'

      # Security scan
      - docker run --network host --rm \
          -v $(pwd)/target:/zap/wrk \
          -e JAVA_OPTS="-Xmx4096m" \
          ${ZAP_IMAGE} \
          zap-baseline.py \
          -t http://localhost:${APP_PORT} \
          -r zap-report.html \
          -x zap-report.xml \
          -J zap-report.json

      # Cleanup
      - kill $(cat app.pid) || true

artifacts:
  files:
    - target/*.jar
    - target/site/**
    - target/*-report.*
    - app.log
  name: devsecops-artifacts-${CODEBUILD_BUILD_ID}
