version: 0.2

env:
  variables:
    REPORT_BUCKET: devsecopspocreports
    JACOCO_REPORT_DIR: target/site/jacoco
    DEPENDENCY_CHECK_REPORT_PATH: target/dependency-check-report.html
  parameter-store:
    SONAR_TOKEN: /devsecops/sonar/token
    SONAR_PROJECT_KEY: /devsecops/sonar/projectKey
    SONAR_ORGANIZATION: /devsecops/sonar/organization

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Pre-build phase started...
      - echo Sonar Project Key: $SONAR_PROJECT_KEY
      - echo Sonar Organization: $SONAR_ORGANIZATION

  build:
    commands:
      - echo Build phase started...
      - mvn clean verify jacoco:report org.owasp:dependency-check-maven:check
      - echo Running SonarCloud analysis...
      - mvn sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_TOKEN

  post_build:
    commands:
      - echo Post-build phase started...
      - echo Listing contents of JaCoCo report directory:
      - ls -R $JACOCO_REPORT_DIR || echo "JaCoCo report directory not found!"
      - echo Uploading JaCoCo report to S3...
      - aws s3 cp $JACOCO_REPORT_DIR s3://$REPORT_BUCKET/reports/jacoco/ --recursive --acl public-read
      - echo Uploading Dependency Check report to S3...
      - aws s3 cp $DEPENDENCY_CHECK_REPORT_PATH s3://$REPORT_BUCKET/reports/dependency-check-report.html --acl public-read

artifacts:
  files:
    - target/*.jar
    - target/*.war
    - $JACOCO_REPORT_DIR/index.html
    - $DEPENDENCY_CHECK_REPORT_PATH
  discard-paths: no
