version: 0.2

env:
  variables:
    REPORT_BUCKET: devsecopspocreports
    JACOCO_REPORT_PATH: target/site/jacoco/index.html
    DEPENDENCY_CHECK_REPORT_PATH: target/dependency-check-report.html
  parameter-store:
    SONAR_TOKEN: /devsecops/sonar/token
    SONAR_PROJECT_KEY: /devsecops/sonar/projectKey
    SONAR_ORGANIZATION: /devsecops/sonar/organization

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Sonar Scanner...
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip
      - unzip sonar-scanner.zip
      - mv sonar-scanner-* sonar-scanner
      - export PATH=$PATH:$(pwd)/sonar-scanner/bin

  pre_build:
    commands:
      - echo Pre-build started

  build:
    commands:
      - echo Starting Maven build...
      - mvn clean verify
      - echo Running SonarCloud scan...
      - sonar-scanner \
          -Dsonar.projectKey=$SONAR_PROJECT_KEY \
          -Dsonar.organization=$SONAR_ORGANIZATION \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
      - echo Generating JaCoCo report...
      - mvn jacoco:report
      - echo Running OWASP Dependency Check...
      - mvn org.owasp:dependency-check-maven:check -Dformat=HTML

  post_build:
    commands:
      - echo Uploading reports to S3...
      - aws s3 cp $JACOCO_REPORT_PATH s3://$REPORT_BUCKET/reports/jacoco/index.html --acl public-read
      - aws s3 cp $DEPENDENCY_CHECK_REPORT_PATH s3://$REPORT_BUCKET/reports/sca/dependency-check-report.html --acl public-read

      - echo Sending SNS email notification...
      - |
        if [ $? -eq 0 ]; then
          mvn exec:exec@send-success-email
        else
          mvn exec:exec@send-failure-email
        fi

artifacts:
  files:
    - target/*.jar
    - target/*.war
    - $JACOCO_REPORT_PATH
    - $DEPENDENCY_CHECK_REPORT_PATH
