version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Entering INSTALL phase...
      - echo Installing Maven...
      - curl -sL https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.zip -o maven.zip
      - unzip maven.zip
      - export M2_HOME=$PWD/apache-maven-3.9.6
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -version

  pre_build:
    commands:
      - echo Entering PRE_BUILD phase...
      - echo Running OWASP Dependency Check...
      - mkdir -p dependency-check
      - curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip -o dc.zip
      - unzip dc.zip -d dependency-check
      - dependency-check/dependency-check/bin/dependency-check.sh --project car-rentals --scan . --format HTML --out .
      - echo Logging in to SonarCloud...
      - export SONAR_TOKEN=$(aws ssm get-parameter --name "sonar-token" --with-decryption --query Parameter.Value --output text)
      - export SONAR_ORG=$(aws ssm get-parameter --name "sonar-org" --with-decryption --query Parameter.Value --output text)

  build:
    commands:
      - echo Entering BUILD phase...
      - mvn clean verify sonar:sonar \
          -Dsonar.projectKey=car-rentals \
          -Dsonar.organization=$SONAR_ORG \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
      - echo Build completed

  post_build:
    commands:
      - echo Entering POST_BUILD phase...
      - echo "Publishing reports to S3..."
      - aws s3 cp target/site/jacoco/index.html s3://devsecopspocreports/reports/jacoco/index.html --acl public-read
      - aws s3 cp dependency-check-report.html s3://devsecopspocreports/reports/dependency-check-report.html --acl public-read

artifacts:
  files:
    - target/*.jar
    - target/*.war
    - target/site/jacoco/**
    - dependency-check-report.html
