version: 0.2

env:
  variables:
    REPORT_BUCKET: devsecopspocreports
    JACOCO_REPORT_DIR: target/site/jacoco
    DEPENDENCY_CHECK_REPORT_PATH: target/dependency-check-report.html

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - yum install -y maven

  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - echo "SonarCloud Project Key: devsecops-poc"
      - echo "SonarCloud Organization: praveenmummella"

  build:
    commands:
      - echo "Build phase started..."
      - mvn clean verify jacoco:report org.owasp:dependency-check-maven:check
      - echo "Running SonarCloud analysis..."
      - mvn sonar:sonar -Dsonar.projectKey=my-project-key -Dsonar.organization=my-org -Dsonar.login=my-token

  post_build:
    commands:
      - echo "Post-build phase started..."
      - echo "Uploading JaCoCo report to S3..."
      - ls -lR $JACOCO_REPORT_DIR || echo "JaCoCo report not found"
      - aws s3 cp $JACOCO_REPORT_DIR s3://$REPORT_BUCKET/reports/jacoco/ --recursive --acl public-read
      - echo "Uploading Dependency Check report to S3..."
      - aws s3 cp $DEPENDENCY_CHECK_REPORT_PATH s3://$REPORT_BUCKET/reports/dependency-check-report.html --acl public-read

artifacts:
  files:
    - target/*.jar
    - target/*.war
    - target/site/jacoco/index.html
    - target/dependency-check-report.html
  discard-paths: no
