version: 0.2

env:
  variables:
    SONAR_PROJECT_KEY: "devsecops-poc"
    APP_PORT: "5000"
    ZAP_IMAGE: "ghcr.io/zaproxy/zaproxy:stable"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      # 1. Verify Docker
      - docker info
      
      # 2. Pull ZAP (with download verification)
      - until docker pull ${ZAP_IMAGE}; do sleep 1; done
      
      # 3. Install SonarScanner (with robust download)
      - curl -sSL --retry 3 --retry-delay 5 -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-latest-linux.zip
      - file sonar-scanner.zip | grep -q "Zip archive data"
      - unzip -qq sonar-scanner.zip -d /opt
      - rm sonar-scanner.zip
      - chmod +x /opt/sonar-scanner-*/bin/*
      - ln -s /opt/sonar-scanner-*/bin/sonar-scanner /usr/local/bin/

  pre_build:
    commands:
      - mvn dependency:go-offline -B

  build:
    commands:
      - mvn -B clean package
      - mvn sonar:sonar \
          -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${SONAR_TOKEN} \
          -Dsonar.java.binaries=target/classes \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      - mvn -B dependency-check:check

  post_build:
    commands:
      # Start app with process control
      - nohup java -jar target/*.jar --server.port=${APP_PORT} > app.log 2>&1 & echo $! > app.pid
      - sleep 20

      # Robust health check
      - for i in {1..10}; do
          if curl -sSf http://localhost:${APP_PORT}/health; then
            echo "App healthy";
            break;
          else
            echo "Waiting... Attempt $i/10";
            sleep 5;
          fi
        done

      # ZAP scan with retries
      - for i in {1..3}; do
          docker run --network host --rm \
            -v $(pwd)/target:/zap/wrk \
            -e JAVA_OPTS="-Xmx4096m" \
            ${ZAP_IMAGE} \
            zap-baseline.py \
            -t http://localhost:${APP_PORT} \
            -r zap-report.html \
            -x zap-report.xml \
            -J zap-report.json && break || sleep 10;
        done

      # Cleanup
      - kill $(cat app.pid) || true

artifacts:
  files:
    - target/*.jar
    - target/site/**
    - target/*-report.*
    - app.log
  name: devsecops-artifacts-${CODEBUILD_BUILD_ID}
