version: 0.2

env:
  variables:
    REPORT_BUCKET: devsecopspocreports
    JACOCO_REPORT_PATH: target/site/jacoco/index.html
    JACOCO_REPORT_DIR: target/site/jacoco
    DEPENDENCY_CHECK_REPORT_PATH: target/dependency-check-report.html
  parameter-store:
    SONAR_TOKEN: /devsecops/sonar/token
    SONAR_PROJECT_KEY: /devsecops/sonar/projectKey
    SONAR_ORGANIZATION: /devsecops/sonar/organization

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - yum install -y maven
      - echo "Installing SonarScanner..."
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip
      - unzip sonar-scanner.zip
      - mv sonar-scanner-* sonar-scanner
      - export PATH=$PATH:$(pwd)/sonar-scanner/bin

  pre_build:
    commands:
      - echo "Project Key: $SONAR_PROJECT_KEY"
      - echo "Organization: $SONAR_ORGANIZATION"

  build:
    commands:
      - echo "Build phase started..."
      - mvn clean verify jacoco:report org.owasp:dependency-check-maven:check
      - echo "Running SonarCloud analysis..."
      - mvn sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_TOKEN

  post_build:
    commands:
      - echo "Post-build phase started..."
      - echo "Listing JaCoCo report directory:"
      - ls -R $JACOCO_REPORT_DIR || echo "JaCoCo report not found!"
      - echo "Uploading JaCoCo report to S3..."
      - aws s3 cp $JACOCO_REPORT_DIR s3://$REPORT_BUCKET/reports/jacoco/ --recursive --acl public-read
      - echo "Uploading OWASP Dependency Check report to S3..."
      - aws s3 cp $DEPENDENCY_CHECK_REPORT_PATH s3://$REPORT_BUCKET/reports/dependency-check-report.html --acl public-read
      - echo "Sending SNS email notification..."
      - mvn exec:exec@send-success-email || mvn exec:exec@send-failure-email
      - echo "Reports successfully uploaded to S3"

artifacts:
  files:
    - "target/*.jar"
    - "target/*.war"
    - "target/site/jacoco/index.html"
    - "target/dependency-check-report.html"
  discard-paths: no
