version: 0.2

env:
  variables:
    REPORT_BUCKET: devsecopspocreports
    JACOCO_REPORT_PATH: target/site/jacoco/index.html
    JACOCO_REPORT_DIR: target/site/jacoco
    DEPENDENCY_CHECK_REPORT_PATH: target/dependency-check-report.html
    OWASP_FAIL_ON_ERROR: "false"
  parameter-store:
    SONAR_TOKEN: /devsecops/sonar/token
    SONAR_PROJECT_KEY: /devsecops/sonar/projectKey
    SONAR_ORGANIZATION: /devsecops/sonar/organization
    NVD_API_KEY: /devsecops/nvd/apikey

phases:
  install:
    runtime-versions:
      java: corretto17
    commands: [
      "echo 'Setting up Ubuntu environment...'",
      "apt-get update -y",
      "apt-get install -y maven unzip docker.io",
      "service docker start",
      "curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip",
      "unzip sonar-scanner.zip",
      "mv sonar-scanner-* sonar-scanner",
      "export PATH=$PATH:$(pwd)/sonar-scanner/bin",
      "mkdir -p $HOME/.dependency-check/data",
      "chmod -R 777 $HOME/.dependency-check"
    ]

  pre_build:
    commands: [
      "echo 'Pre-build phase started...'",
      "echo 'Project Key: $SONAR_PROJECT_KEY'",
      "echo 'Organization: $SONAR_ORGANIZATION'",
      "mkdir -p target/site/jacoco"
    ]

  build:
    commands: [
      "echo 'Build phase started...'",
      "mvn clean package",
      "mvn jacoco:report",
      "mvn org.owasp:dependency-check-maven:check -Dnvd.api.key=$NVD_API_KEY -Dnvd.api.delay=6000 -DfailOnError=$OWASP_FAIL_ON_ERROR || echo 'Dependency check completed with warnings'",
      "mvn sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_TOKEN || echo 'Sonar analysis completed with warnings'"
    ]

  post_build:
    commands: [
      "echo 'Post-build phase started...'",
      "echo 'Checking reports...'",
      "[ -d $JACOCO_REPORT_DIR ] && aws s3 cp $JACOCO_REPORT_DIR s3://$REPORT_BUCKET/reports/jacoco/ --recursive --acl public-read || echo 'JaCoCo report not found'",
      "[ -f $DEPENDENCY_CHECK_REPORT_PATH ] && aws s3 cp $DEPENDENCY_CHECK_REPORT_PATH s3://$REPORT_BUCKET/reports/ --acl public-read || echo 'Dependency check report not found'",
      "echo 'Sending email notification...'",
      "if [ $? -eq 0 ]; then mvn exec:exec@send-success-email; else mvn exec:exec@send-failure-email; fi"
    ]

artifacts:
  files: [
    "target/*.jar",
    "target/*.war",
    "target/site/jacoco/index.html",
    "target/dependency-check-report.html"
  ]
  name: devsecops-artifacts
  discard-paths: no
