version: 0.2

env:
  variables:
    REPORT_BUCKET: devsecopspocreports
    # Changed to relative paths to avoid issues
    JACOCO_REPORT_DIR: target/site/jacoco
    DEPENDENCY_CHECK_REPORT: target/dependency-check-report.html
    # Added Java version control
    JAVA_VERSION: 17
    MAVEN_OPTS: -Dmaven.compiler.release=17

phases:
  install:
    runtime-versions:
      java: corretto17  # Matches JAVA_VERSION
    commands:
      - echo "Installing dependencies..."
      - yum install -y maven docker
      - service docker start
      - echo "Java version: $(java -version 2>&1 | head -1)"
      - echo "Maven version: $(mvn -version | head -1)"

  pre_build:
    commands:
      - echo "Pre-build configuration..."
      - mkdir -p target/site/jacoco  # Ensure directory exists

  build:
    commands:
      - echo "Building with Java ${JAVA_VERSION}..."
      - >
        mvn clean verify 
        jacoco:report 
        org.owasp:dependency-check-maven:aggregate 
        -Dmaven.compiler.release=${JAVA_VERSION} 
        -DfailOnError=false
      - echo "Build completed with status $?"

  post_build:
    commands:
      - echo "Post-build processing..."
      # Jacoco report handling
      - |
        if [ -d "$JACOCO_REPORT_DIR" ]; then
          echo "Uploading JaCoCo reports..."
          aws s3 cp $JACOCO_REPORT_DIR s3://$REPORT_BUCKET/reports/jacoco/ --recursive --acl public-read
        else
          echo "Warning: JaCoCo report directory not found"
        fi
      # Dependency check handling  
      - |
        if [ -f "$DEPENDENCY_CHECK_REPORT" ]; then
          echo "Uploading Dependency Check report..."
          aws s3 cp $DEPENDENCY_CHECK_REPORT s3://$REPORT_BUCKET/reports/ --acl public-read
        else
          echo "Warning: Dependency Check report not found"
        fi

artifacts:
  files:
    - "target/*.jar"
    - "target/*.war"
    - "target/site/jacoco/**/*"
    - "target/dependency-check-report.html"
  name: devsecops-artifacts
  discard-paths: no  # Preserve directory structure
