version: 0.2

env:
  variables:
    REPORT_BUCKET: devsecopspocreports
    JACOCO_REPORT_PATH: target/site/jacoco/index.html
    JACOCO_REPORT_DIR: target/site/jacoco
    DEPENDENCY_CHECK_REPORT_PATH: target/dependency-check-report.html
  parameter-store:
    SONAR_TOKEN: /devsecops/sonar/token
    SONAR_PROJECT_KEY: /devsecops/sonar/projectKey
    SONAR_ORGANIZATION: /devsecops/sonar/organization

phases:
  install:
    runtime-versions:
      java: corretto17
    commands: [
      "echo 'Installing Maven and SonarScanner...'",
      "apt-get update -y",
      "apt-get install -y maven unzip",
      "curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006.zip",
      "unzip sonar-scanner.zip",
      "mv sonar-scanner-* sonar-scanner",
      "export PATH=$PATH:$(pwd)/sonar-scanner/bin"
    ]

  pre_build:
    commands: [
      "echo 'Pre-build phase started...'",
      "echo 'Project Key: $SONAR_PROJECT_KEY'",
      "echo 'Organization: $SONAR_ORGANIZATION'"
    ]

  build:
    commands: [
      "echo 'Build phase started...'",
      "mvn clean verify jacoco:report org.owasp:dependency-check-maven:check",
      "sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN"
    ]

  post_build:
    commands: [
      "echo 'Post-build phase started...'",
      "BUILD_SUCCESS=true",
      "echo 'Uploading JaCoCo report to S3...'",
      "aws s3 cp $JACOCO_REPORT_DIR s3://$REPORT_BUCKET/reports/jacoco/ --recursive --acl public-read || BUILD_SUCCESS=false",
      "echo 'Uploading Dependency Check report to S3...'",
      "aws s3 cp $DEPENDENCY_CHECK_REPORT_PATH s3://$REPORT_BUCKET/reports/dependency-check-report.html --acl public-read || BUILD_SUCCESS=false",
      "if [ \"$BUILD_SUCCESS\" = true ]; then echo 'Sending success SNS notification...'; mvn exec:exec@send-success-email; else echo 'Sending failure SNS notification...'; mvn exec:exec@send-failure-email; fi",
      "echo 'Post-build steps completed.'"
    ]

artifacts:
  files:
    - "target/*.jar"
    - "target/*.war"
    - "$JACOCO_REPORT_PATH"
    - "$JACOCO_REPORT_DIR/index.html"
    - "$DEPENDENCY_CHECK_REPORT_PATH"
  discard-paths: no
