version: 0.2

env:
  variables:
    S3_BUCKET: "devsecopspocreports"
    SONAR_PROJECT_KEY: "devsecops-poc"
    SONAR_ORGANIZATION: "praveenmummella"
    SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:310188667383:build-notifications"
  parameter-store:
    SONAR_TOKEN: "/devsecops/sonar/token"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - yum install -y maven

  pre_build:
    commands:
      - echo "Running OWASP Dependency Check (SCA)..."
      - mvn org.owasp:dependency-check-maven:check

  build:
    commands:
      - echo "Building and testing the application..."
      - mvn clean verify
      - echo "Generating JaCoCo code coverage report..."
      - mvn jacoco:report
      - echo "Running SonarCloud analysis..."
      - mvn sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

  post_build:
    commands:
      - echo "Uploading reports to S3..."
      - aws s3 cp target/site/jacoco/index.html s3://$S3_BUCKET/reports/jacoco/index.html --acl public-read || echo "JaCoCo report not found."
      - aws s3 cp target/dependency-check-report.html s3://$S3_BUCKET/reports/dependency-check-report.html --acl public-read || echo "SCA report not found."
      - |
        echo "Sending SNS notification..."
        SUBJECT="Build Notification: $CODEBUILD_BUILD_SUCCEEDING"
        MESSAGE="Build Completed. Reports available at:\n"
        MESSAGE+="JaCoCo Report: https://$S3_BUCKET.s3.amazonaws.com/reports/jacoco/index.html\n"
        MESSAGE+="SCA Report: https://$S3_BUCKET.s3.amazonaws.com/reports/dependency-check-report.html\n"
        aws sns publish --topic-arn $SNS_TOPIC_ARN --subject "$SUBJECT" --message "$MESSAGE"

artifacts:
  files:
    - target/*.jar
    - target/*.war
    - target/site/jacoco/**
    - target/dependency-check-report.html
